<?php

namespace AppBundle\Repository;

/**
 * EkintzaMotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EkintzaMotaRepository extends \Doctrine\ORM\EntityRepository
{
}
