<?php

namespace AppBundle\Repository;

/**
 * EkintzamotadetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EkintzamotadetRepository extends \Doctrine\ORM\EntityRepository
{
}
