<?php

namespace AppBundle\Repository;

/**
 * TxostenaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TxostenaRepository extends \Doctrine\ORM\EntityRepository
{
}
