<?php

namespace AppBundle\Repository;

/**
 * TxostenadetvalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TxostenadetvalRepository extends \Doctrine\ORM\EntityRepository
{
}
