<?php

namespace AppBundle\Repository;

/**
 * TxostenadetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TxostenadetRepository extends \Doctrine\ORM\EntityRepository
{
}
